### PR TITLE
start adding my own research and stuff

### PR DESCRIPTION
**Pull request by applecuckoo**
Just starting a PR here so I can start adding file documentation, ImHex patterns and other things.

I've already mentioned this, but I use [ImHex](https://imhex.werwolv.net/) for practically all of my reverse engineering projects - its custom [Pattern Language](https://docs.werwolv.net/pattern-language) is really useful for defining file structures and things. I've really gotten used to writing with it over the past few months, which is also right about when I found LFHacks here on GitHub :)

By the way, I've marked this as a draft so it can only get merged when I've approved it on my end.

And yes, I ripped that InLight logo from Photo Fun Ultra - their engine seems to be tiled without any bleed, so it's trivial to reassemble their sprites in Aseprite

### CODE REVIEW

**Comment by BLiNXthetimesweeperGOD** [comment]
Please note:
The Leapster RIB is still a work in progress (I started it late last night). Thanks for the help here though!
Each index table in the groups referenced by the RIB has a slightly different structure and works a little differently to the last, so it'll take a while to document them all. After documenting the structure of the groups (that's actually fairly consistent if you ignore the IDs), I'll probably resume work with the IDs, as those are used to identify what index table is what.

**Comment by applecuckoo** [comment]
@BLiNXthetimesweeperGOD I should point out I had actually kind of started that ImHex pattern a few days ago and I was basing it on LeapSplit at the time, lol. Having an actual file struct doc to base it off of helps a lot, so thanks!

**Comment by BLiNXthetimesweeperGOD** [comment]
Good to know! Glad someone was able to read my code.

**Comment by applecuckoo** [comment]
@BLiNXthetimesweeperGOD Hi - this PR is all good to go now, you should be able to merge in my edits. Same for your LeapFrog credits repo.

**Pull request merged**
